# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that AES encrypts an application layer and then decrypts it at launch time"
  homepage = "https://github.com/paketo-buildpacks/encrypt-at-rest"
  id = "paketo-buildpacks/encrypt-at-rest"
  keywords = ["AES", "encrypt-at-rest"]
  name = "Paketo Buildpack for Encrypt-at-Rest"
  version = "{{.version}}"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]


  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/encrypt-at-rest/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    description = "the AES hex encoded encryption key"
    launch = true
    name = "BPL_EAR_KEY"

  [[metadata.configurations]]
    build = true
    description = "the AES hex encoded encryption key"
    name = "BP_EAR_KEY"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"

[[targets]]
arch = "amd64"
os = "linux"

[[targets]]
arch = "arm64"
os = "linux"